sudo: required
services:
  - dcoker

before_install:
  - docker build -t taip2410/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run taip2410/react-test npm test -- --coverage

after_success:
  - docker build -t taip2410/multi-client ./client
  - docker build -t taip2410/multi-nginx ./nginx
  - docker build -t taip2410/multi-server ./server
  - docker build -t taip2410/multi-worker ./worker
  #Take those images and push them to docker hub

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push taip2410/multi-client
  - docker push taip2410/multi-nginx
  - docker push taip2410/multi-server
  - docker push taip2410/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-mult'
  on:
    branch:master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY